name: cd
on:
  push:
    branches:
      - master
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  push-to-ecr:
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - run: |
          echo "New version is ${VERSION}"
      - run: |
          echo "New version is ${{ env.VERSION }}"
      - name: Deploying new image to ECR 
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ENVIRONMENT: dev
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          AWHERE_ENCODED_KEY: ${{ secrets.AWHERE_ENCODED_KEY }}
          AWHERE_TOKEN_URL: ${{ secrets.AWHERE_TOKEN_URL }}
        run: make push-to-ecr tag=${{ env.VERSION }}